# Generated by Django 4.2.7 on 2023-11-06 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('executionid', models.CharField(blank=True, db_column='ExecutionID', max_length=15, null=True)),
                ('accounttype', models.CharField(blank=True, db_column='AccountType', max_length=1, null=True)),
                ('symbol', models.CharField(db_column='Symbol', default='', max_length=6, primary_key=True, serialize=False)),
                ('symbolname', models.CharField(blank=True, db_column='symbolName', max_length=15, null=True, verbose_name='Stock name')),
                ('exchange', models.CharField(blank=True, db_column='Exchange', max_length=1, null=True)),
                ('exchangename', models.CharField(blank=True, db_column='ExchangeName', max_length=15, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=1, max_digits=12, null=True)),
                ('leavesqty', models.DecimalField(blank=True, db_column='LeavesQty', decimal_places=1, max_digits=12, null=True)),
                ('holdqty', models.DecimalField(blank=True, db_column='HoldQty', decimal_places=1, max_digits=12, null=True)),
                ('side', models.CharField(blank=True, db_column='Side', max_length=1, null=True)),
                ('currentprice', models.DecimalField(blank=True, db_column='CurrentPrice', decimal_places=1, max_digits=12, null=True)),
                ('valuation', models.DecimalField(blank=True, db_column='Valuation', decimal_places=1, max_digits=12, null=True)),
                ('profitloss', models.DecimalField(blank=True, db_column='ProfitLoss', decimal_places=1, max_digits=12, null=True)),
                ('profitlossrate', models.DecimalField(blank=True, db_column='ProfitLossRate', decimal_places=1, max_digits=12, null=True)),
                ('SymbolDisp', models.CharField(blank=True, max_length=40, verbose_name='sName')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('ExecutionDay', models.DateField(null=True)),
                ('DeliveryDay', models.DateField(null=True)),
                ('Exchange', models.IntegerField(null=True)),
                ('ExchangeName', models.CharField(default='', max_length=6)),
                ('Symbol', models.CharField(default='', max_length=6)),
                ('symbolName', models.CharField(max_length=40, null=True, verbose_name='タイトル')),
                ('Side', models.IntegerField(null=True)),
                ('Qty', models.IntegerField(null=True)),
                ('Price', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('Valuation', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('PointUse', models.BooleanField(default=False)),
                ('Commission', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('AccountType', models.IntegerField(null=True)),
                ('ProfitLoss', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('CurrentPrice', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('stock_record', models.ForeignKey(default='111', on_delete=django.db.models.deletion.PROTECT, related_name='Stock_record', to='stock.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Trade',
            },
        ),
    ]
