# Generated by Django 4.2.7 on 2023-11-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbolname',
            new_name='symbolName',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='SymbolDisp',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='holding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='period',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='stock',
            name='period_type',
            field=models.CharField(default='day', max_length=10, verbose_name='期間表示タイプ'),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbolAlias',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbolDisp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='sName'),
        ),
    ]
