# Generated by Django 4.2.7 on 2023-11-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.IntegerField(db_column='symbol', default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.IntegerField(default=0),
        ),
    ]
