# Generated by Django 4.1 on 2022-09-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='content',
        ),
        migrations.AddField(
            model_name='stock',
            name='AccountType',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Commission',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='CommissionTax',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='CurrentPrice',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Exchange',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ExchangeName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ExecutionDay',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ExecutionID',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Expenses',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ExpireDay',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='HoldQty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='LeavesQty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='MarginTradeType',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ProfitLoss',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ProfitLossRate',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Side',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Symbol',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='SymbolName',
            field=models.CharField(max_length=40, null=True, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='stock',
            name='Valuation',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
