# Generated by Django 4.2.7 on 2023-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='SymbolDisp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='sName'),
        ),
    ]
