# Generated by Django 4.2.7 on 2023-11-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_symbol_alter_trade_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
