# Generated by Django 4.1 on 2022-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_content_stock_accounttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False),
        ),
    ]
