# Generated by Django 4.1 on 2022-09-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_id_alter_stock_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='AccountType',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Commission',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='CommissionTax',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='CurrentPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Exchange',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ExchangeName',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ExecutionDay',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ExecutionID',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Expenses',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ExpireDay',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='HoldQty',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='MarginTradeType',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ProfitLoss',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ProfitLossRate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Side',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Valuation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
    ]
