# Generated by Django 4.2.7 on 2023-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_user_stock_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.CharField(default='', max_length=25, primary_key=True, serialize=False)),
                ('State', models.SmallIntegerField(null=True)),
                ('OrderState', models.SmallIntegerField(null=True)),
                ('OrdType', models.SmallIntegerField(null=True)),
                ('RecvTime', models.DateTimeField(null=True)),
                ('Symbol', models.IntegerField(default=0)),
                ('SymbolName', models.CharField(max_length=40, null=True, verbose_name='タイトル')),
                ('Exchange', models.CharField(blank=True, db_column='Exchange', max_length=1, null=True)),
                ('ExchangeName', models.CharField(blank=True, db_column='ExchangeName', max_length=15, null=True)),
                ('Price', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('OrderQty', models.IntegerField(null=True)),
                ('CumQty', models.IntegerField(null=True)),
                ('Side', models.SmallIntegerField(null=True)),
                ('AccountType', models.SmallIntegerField(null=True)),
                ('DelivType', models.SmallIntegerField(null=True)),
                ('ExpireDay', models.DateField(null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
