# Generated by Django 4.2.7 on 2023-11-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
    ]
