# Generated by Django 4.2.7 on 2023-11-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='SymbolAlias',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Alias'),
        ),
    ]
