# Generated by Django 4.2.7 on 2023-11-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_symbolalias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='SymbolAlias',
            new_name='symbolAlias',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='SymbolDisp',
            new_name='symbolDisp',
        ),
    ]
