# Generated by Django 4.2.7 on 2023-11-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_trade_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='PointUse',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
