# Generated by Django 4.2.7 on 2023-11-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_rename_symbolalias_stock_symbolalias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbolname',
            new_name='symbolName',
        ),
    ]
