# Generated by Django 4.2.7 on 2023-11-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_trade_pointuse_alter_trade_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbolAlias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.company'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ExchangeName',
            field=models.CharField(default=0, max_length=6, null=True),
        ),
    ]
