# Generated by Django 4.1 on 2022-09-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_created_at_stock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='CurrentPrice',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ProfitLoss',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ProfitLossRate',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Valuation',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
