# Generated by Django 4.2.7 on 2023-11-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stock_symbolalias_alter_trade_exchangename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbolAlias',
            new_name='company',
        ),
    ]
