# Generated by Django 4.2.7 on 2023-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_rename_symbolalias_stock_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='symbolAlias',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Alias'),
        ),
    ]
