# Generated by Django 4.1 on 2022-09-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stock_currentprice_stock_profitloss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='CurrentPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ProfitLoss',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ProfitLossRate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Valuation',
        ),
    ]
