# Generated by Django 4.1 on 2022-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stock_currentprice_stock_profitloss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Valuation',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
