# Generated by Django 4.1 on 2022-09-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_stock_held'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='holding',
        ),
    ]
