# Generated by Django 4.1 on 2022-09-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_stock_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='holding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='holding',
            field=models.BooleanField(default=False),
        ),
    ]
