/* 11:32:47 さくら */ SHOW VARIABLES;
/* 11:32:47 さくら */ SET information_schema_stats_expiry=0;
/* 11:32:47 さくら */ SELECT @@global.max_allowed_packet;
/* 11:32:47 さくら */ USE `stockdb`;
/* 11:32:47 さくら stockdb */ SHOW VARIABLES LIKE 'skip_show_database';
/* 11:32:47 さくら stockdb */ SHOW DATABASES;
/* 11:32:47 さくら stockdb */ SHOW FULL TABLES;
/* 11:32:47 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 11:32:47 さくら stockdb */ SHOW VARIABLES LIKE 'character_set_database';
/* 11:32:52 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 11:32:52 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 11:32:52 さくら stockdb */ SHOW INDEX FROM `stock_trade`;
/* 11:32:52 さくら stockdb */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 11:32:52 さくら stockdb */ SELECT COUNT(1) FROM `stock_trade`;
/* 11:32:52 さくら stockdb */ SELECT * FROM `information_schema`.`collations` WHERE character_set_name = 'utf8mb4' ORDER BY `collation_name` ASC;
/* 11:34:39 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `SymbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 11:34:39 さくら stockdb */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 11:34:39 さくら stockdb */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES') AND Engine != 'PERFORMANCE_SCHEMA';
/* 11:34:46 さくら stockdb */ SHOW FULL TABLES;
/* 11:34:46 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 11:34:46 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 11:34:46 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 11:34:46 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `SymbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 11:46:35 さくら */ SHOW VARIABLES;
/* 11:46:35 さくら */ SET information_schema_stats_expiry=0;
/* 11:46:35 さくら */ SELECT @@global.max_allowed_packet;
/* 11:46:35 さくら */ USE `stockdb`;
/* 11:46:35 さくら stockdb */ SHOW VARIABLES LIKE 'skip_show_database';
/* 11:46:35 さくら stockdb */ SHOW DATABASES;
/* 11:46:35 さくら stockdb */ SHOW FULL TABLES;
/* 11:46:35 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 11:46:35 さくら stockdb */ SHOW VARIABLES LIKE 'character_set_database';
/* 11:46:38 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 11:46:38 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 11:46:38 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 11:46:38 さくら stockdb */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 11:46:38 さくら stockdb */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES') AND Engine != 'PERFORMANCE_SCHEMA';
/* 11:46:38 さくら stockdb */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 11:46:38 さくら stockdb */ SELECT * FROM `information_schema`.`collations` WHERE character_set_name = 'utf8mb4' ORDER BY `collation_name` ASC;
/* 11:46:45 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` ORDER BY `holding` LIMIT 0,1000;
/* 11:46:48 さくら stockdb */ SHOW COLUMNS FROM `stock_stock`;
/* 11:46:55 さくら stockdb */ UPDATE `stock_stock` SET `holding` = '1' WHERE `Symbol` = '2168';
/* 11:47:45 さくら stockdb */ UPDATE `stock_stock` SET `holding` = '1' WHERE `Symbol` = '2168';
/* 11:48:35 さくら stockdb */ UPDATE `stock_stock` SET `holding` = '1' WHERE `Symbol` = '2168';
/* 11:49:25 さくら stockdb */ UPDATE `stock_stock` SET `holding` = '1' WHERE `Symbol` = '2168';
/* 11:50:16 さくら stockdb */ UPDATE `stock_stock` SET `holding` = '1' WHERE `Symbol` = '2168';
/* 11:51:07 さくら stockdb */ UPDATE `stock_stock` SET `holding` = '1' WHERE `Symbol` = '2168';
/* 11:51:57 さくら stockdb */ UPDATE `stock_stock` SET `holding` = '1' WHERE `Symbol` = '2168';
/* 13:01:46 さくら stockdb */ SHOW VARIABLES;
/* 13:01:46 さくら stockdb */ SET information_schema_stats_expiry=0;
/* 13:01:46 さくら stockdb */ SELECT @@global.max_allowed_packet;
/* 13:01:46 さくら stockdb */ USE `stockdb`;
/* 13:01:46 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 13:01:46 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 13:01:46 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `SymbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 13:01:48 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:01:48 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:01:48 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` ORDER BY `holding` LIMIT 0,1000;
/* 13:01:50 さくら stockdb */ SHOW FULL TABLES;
/* 13:01:50 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 13:01:50 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:01:50 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:01:50 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 13:03:07 さくら stockdb */ SHOW FULL TABLES;
/* 13:03:07 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 13:03:07 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:03:08 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:03:08 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 13:07:00 さくら stockdb */ SHOW FULL TABLES;
/* 13:07:00 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 13:07:00 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:07:00 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:07:00 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 13:14:19 さくら stockdb */ SHOW FULL TABLES;
/* 13:14:19 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 13:14:19 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:14:19 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:14:19 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 13:21:18 さくら stockdb */ DROP TABLE `stock_stock`;
/* 13:21:20 さくら stockdb */ SHOW FULL TABLES;
/* 13:21:20 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 13:22:46 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:22:46 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:22:46 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 13:22:56 さくら stockdb */ DROP TABLE `stock_stock`;
/* 13:23:07 さくら stockdb */ SHOW FULL TABLES;
/* 13:23:07 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 13:23:15 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:23:15 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:23:15 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 13:23:23 さくら stockdb */ TRUNCATE TABLE `stock_stock`;
/* 13:23:23 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `SymbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `symbolDisp`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `symbolAlias`, `holding` FROM `stock_stock` LIMIT 0,1000;
/* 13:42:26 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:46:55 さくら */ SHOW VARIABLES;
/* 13:46:55 さくら */ SET information_schema_stats_expiry=0;
/* 13:46:55 さくら */ SELECT @@global.max_allowed_packet;
/* 13:46:55 さくら */ USE `stockdb`;
/* 13:46:56 さくら stockdb */ SHOW VARIABLES LIKE 'skip_show_database';
/* 13:46:56 さくら stockdb */ SHOW DATABASES;
/* 13:46:56 さくら stockdb */ SHOW FULL TABLES;
/* 13:46:56 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 13:46:56 さくら stockdb */ SHOW VARIABLES LIKE 'character_set_database';
/* 13:47:00 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 13:47:00 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 13:47:00 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp` FROM `stock_stock` LIMIT 0,1000;
/* 13:47:01 さくら stockdb */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 13:47:01 さくら stockdb */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES') AND Engine != 'PERFORMANCE_SCHEMA';
/* 13:47:01 さくら stockdb */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 13:47:01 さくら stockdb */ SELECT * FROM `information_schema`.`collations` WHERE character_set_name = 'utf8mb4' ORDER BY `collation_name` ASC;
/* 13:47:04 さくら stockdb */ SHOW INDEX FROM `stock_stock`;
/* 14:06:48 さくら stockdb */ SHOW VARIABLES;
/* 14:06:48 さくら stockdb */ SET information_schema_stats_expiry=0;
/* 14:06:48 さくら stockdb */ SELECT @@global.max_allowed_packet;
/* 14:06:49 さくら stockdb */ USE `stockdb`;
/* 14:06:49 さくら stockdb */ SHOW FULL TABLES;
/* 14:06:49 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 14:06:49 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 14:06:49 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 14:06:49 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp` FROM `stock_stock` LIMIT 0,1000;
/* 14:06:52 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 14:06:52 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 14:06:52 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `symbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 14:06:55 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 14:06:55 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 14:06:55 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp` FROM `stock_stock` LIMIT 0,1000;
/* 14:08:02 さくら stockdb */ SHOW FULL TABLES;
/* 14:08:02 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 14:08:02 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 14:08:02 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 14:08:02 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp` FROM `stock_stock` LIMIT 0,1000;
/* 14:24:24 さくら stockdb */ SHOW TABLE STATUS LIKE 'accounts_customuser_user_permissions';
/* 14:24:24 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`accounts_customuser_user_permissions`;
/* 14:24:24 さくら stockdb */ SELECT `id`, `customuser_id`, `permission_id` FROM `accounts_customuser_user_permissions` LIMIT 0,1000;
/* 14:24:28 さくら stockdb */ SHOW TABLE STATUS LIKE 'accounts_customuser';
/* 14:24:28 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`accounts_customuser`;
/* 14:24:28 さくら stockdb */ SELECT `id`, `password`, `last_login`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined` FROM `accounts_customuser` LIMIT 0,1000;
/* 14:30:31 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 14:30:31 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 14:30:31 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp`, `user_id` FROM `stock_stock` LIMIT 0,1000;
/* 14:35:37 さくら stockdb */ DELETE FROM `stock_stock` WHERE `Symbol` IN ('6758','6993','7012','7013','7752','8316','9101','9119','9142','9501','9503');
/* 14:35:51 さくら stockdb */ SHOW FULL TABLES;
/* 14:35:51 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 14:35:52 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 14:35:52 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 14:35:52 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp`, `user_id` FROM `stock_stock` LIMIT 0,1000;
/* 14:36:08 さくら stockdb */ SHOW FULL TABLES;
/* 14:36:08 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 14:36:08 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 14:36:08 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 14:36:08 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp`, `user_id` FROM `stock_stock` LIMIT 0,1000;
/* 15:03:25 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 15:03:25 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 15:03:25 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `symbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 16:53:06 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 16:53:06 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 16:53:06 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp`, `user_id` FROM `stock_stock` LIMIT 0,1000;
/* 16:53:35 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 16:53:35 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 16:53:36 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `symbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 2:43:05 さくら */ SHOW VARIABLES;
/* 2:43:05 さくら */ SET information_schema_stats_expiry=0;
/* 2:43:05 さくら */ SELECT @@global.max_allowed_packet;
/* 2:43:05 さくら */ USE `stockdb`;
/* 2:43:05 さくら stockdb */ SHOW VARIABLES LIKE 'skip_show_database';
/* 2:43:06 さくら stockdb */ SHOW DATABASES;
/* 2:43:06 さくら stockdb */ SHOW FULL TABLES;
/* 2:43:06 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 2:43:06 さくら stockdb */ SHOW VARIABLES LIKE 'character_set_database';
/* 2:43:08 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 2:43:08 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 2:43:08 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `symbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 2:43:08 さくら stockdb */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 2:43:08 さくら stockdb */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES') AND Engine != 'PERFORMANCE_SCHEMA';
/* 2:43:08 さくら stockdb */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 2:43:08 さくら stockdb */ SELECT * FROM `information_schema`.`collations` WHERE character_set_name = 'utf8mb4' ORDER BY `collation_name` ASC;
/* 2:44:06 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 2:44:06 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 2:44:06 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp`, `user_id` FROM `stock_stock` LIMIT 0,1000;
/* 3:11:02 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 3:11:02 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 3:11:02 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `symbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 3:21:24 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 3:21:24 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 3:21:24 さくら stockdb */ SELECT `ExecutionID`, `AccountType`, `Symbol`, `symbolName`, `Exchange`, `ExchangeName`, `Price`, `LeavesQty`, `HoldQty`, `Side`, `CurrentPrice`, `Valuation`, `ProfitLoss`, `ProfitLossRate`, `comment`, `title`, `photo1`, `photo2`, `photo3`, `created_at`, `updated_at`, `holding`, `period`, `period_type`, `symbolAlias`, `symbolDisp`, `user_id` FROM `stock_stock` LIMIT 0,1000;
/* 11:25:41 さくら stockdb */ SHOW VARIABLES;
/* 11:25:41 さくら stockdb */ SET information_schema_stats_expiry=0;
/* 11:25:41 さくら stockdb */ SELECT @@global.max_allowed_packet;
/* 11:25:41 さくら stockdb */ USE `stockdb`;
/* 11:25:41 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 11:25:41 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 11:25:41 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `symbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 11:32:16 さくら stockdb */ SHOW VARIABLES LIKE 'character_set_server';
/* 11:32:16 さくら stockdb */ SHOW VARIABLES LIKE 'collation_server';
/* 11:32:50 さくら stockdb */ CREATE DATABASE `stock_code`;
/* 11:32:50 さくら stockdb */ SHOW DATABASES;
/* 11:32:50 さくら stockdb */ USE `stock_code`;
/* 11:32:50 さくら stock_code */ SHOW VARIABLES LIKE 'character_set_database';
/* 11:32:50 さくら stock_code */ SHOW FULL TABLES;
/* 11:32:50 さくら stock_code */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stock_code' ORDER BY routine_name;
/* 11:36:03 さくら stock_code */ USE `stockdb`;
/* 11:36:03 さくら stockdb */ SHOW VARIABLES LIKE 'character_set_database';
/* 11:36:03 さくら stockdb */ SHOW FULL TABLES;
/* 11:36:03 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 11:36:09 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 11:36:09 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 11:36:09 さくら stockdb */ SELECT `id`, `ExecutionDay`, `DeliveryDay`, `Exchange`, `ExchangeName`, `Symbol`, `symbolName`, `Side`, `Qty`, `Price`, `Valuation`, `PointUse`, `Commission`, `AccountType`, `ProfitLoss`, `CurrentPrice`, `comment`, `created_at`, `updated_at`, `stock_record_id`, `user_id` FROM `stock_trade` LIMIT 0,1000;
/* 11:36:09 さくら stockdb */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 11:36:09 さくら stockdb */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES') AND Engine != 'PERFORMANCE_SCHEMA';
/* 11:36:09 さくら stockdb */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 11:38:39 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 11:38:39 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 11:38:39 さくら stockdb */ SELECT COUNT(1) FROM `stock_stock`;
/* 11:38:42 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_trade';
/* 11:38:42 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_trade`;
/* 11:38:42 さくら stockdb */ SELECT COUNT(1) FROM `stock_trade`;
/* 11:38:43 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 11:38:43 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 11:38:43 さくら stockdb */ SELECT COUNT(1) FROM `stock_stock`;
/* 11:38:45 さくら stockdb */ SHOW INDEX FROM `stock_stock`;
/* 16:24:56 さくら stockdb */ SHOW VARIABLES;
/* 16:24:56 さくら stockdb */ SET information_schema_stats_expiry=0;
/* 16:24:56 さくら stockdb */ SELECT @@global.max_allowed_packet;
/* 16:24:56 さくら stockdb */ USE `stockdb`;
/* 16:24:56 さくら stockdb */ SHOW FULL TABLES;
/* 16:24:56 さくら stockdb */ SELECT * FROM information_schema.routines WHERE routine_schema = 'stockdb' ORDER BY routine_name;
/* 16:24:56 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_stock';
/* 16:24:56 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_stock`;
/* 16:24:56 さくら stockdb */ SHOW INDEX FROM `stock_stock`;
/* 16:24:56 さくら stockdb */ SELECT COUNT(1) FROM `stock_stock`;
/* 16:25:48 さくら stockdb */ SHOW TABLE STATUS LIKE 'stock_company';
/* 16:25:48 さくら stockdb */ SHOW CREATE TABLE `stockdb`.`stock_company`;
/* 16:25:48 さくら stockdb */ SHOW INDEX FROM `stock_company`;
/* 16:25:48 さくら stockdb */ SELECT COUNT(1) FROM `stock_company`;
